# Generated by Django 5.0.2 on 2024-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
