# Generated by Django 5.0.2 on 2024-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
