# Generated by Django 5.0.4 on 2024-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
    ]
